version: '3'
name: "spark_conda"

services:
  mssql:
    container_name: spark-mssql
    build:
      context: ../shared
      dockerfile: Dockerfile.sql-server
    image: mssql:2019
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MostSecretPW!
    ports:
      - 1433:1433
    volumes:
      - "./container_data/mssql/log:/var/opt/mssql/log"
      - "./container_data/mssql/data:/var/opt/mssql/data"
      - "./container_data/mssql/secrets:/var/opt/mssql/secrets"
  
  hive-metastore:
    container_name: spark-hive-metastore
    build:
      context: ./shared
      dockerfile: Dockerfile.hive
    entrypoint: /scripts/init-hive.sh
    image: hive:2.3.9
    ports:
      - 10000:10000
      - 9083:9083
    links:
      - "mssql:mssql"
    volumes:
      - "./container_data/hive/warehouse:/shared_data/hive/warehouse"
    depends_on:
      - mssql

  conda_spark:
    container_name: spark-conda
    build: 
      context: .
      dockerfile: ./spark_conda/Dockerfile.conda
      args:
        - SPARK_VERSION=3.2.1
        - HADOOP_VERSION=2.7
    image: spark-conda:3.2.1
    ports: 
      - 5567:5567
      - 4040:4040
    volumes:
      - "../:/workspace"
      - "./container_data/table_data:/shared_data/table_data"
      - "./container_data/hive/warehouse:/shared_data/hive/warehouse"
    links:
      - "mssql:mssql"
      - "hive-metastore:hive-metastore"