version: '3'

services:
  postgres:
    container_name: spark_postgres
    build:
      context: ./shared
      dockerfile: Dockerfile.postgres
      args: 
        - HIVE_USER_PASSWORD=Supersecretpassw0rd!
    image: pgsql:15.1
    environment:
      - POSTGRES_PASSWORD=MostSecretPW!
    ports:
      - 5432:5432
    volumes:
      - "./container_data/postgres/data:/var/lib/postgresql/data"

  mssql:
    container_name: spark-mssql
    build:
      context: ./shared
      dockerfile: Dockerfile.sql-server
      args:
        - HIVE_USER_PASSWORD=Supersecretpassw0rd!
        - SA_PW=MostSecretPW!
    image: mssql:2019
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - "./container_data/mssql/log:/var/opt/mssql/log"
      - "./container_data/mssql/data:/var/opt/mssql/data"
      - "./container_data/mssql/secrets:/var/opt/mssql/secrets"

  minio-lake:
    container_name: spark-minio-lake
    build:
      context: ./shared
      dockerfile: Dockerfile.minio
      args:
        - HIVE_USER_PASSWORD=Supersecretpassw0rd!
        - MINIO_ROOT_USER=minio_user
        - MINIO_ROOT_PASSWORD=minio_password
    image: minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - "./container_data/minio/lake:/data"
  
  hive-metastore:
    container_name: spark-hive-metastore
    build:
      context: ./shared
      dockerfile: Dockerfile.hive
      args:
        - HIVE_USER_PASSWORD=Supersecretpassw0rd!
    entrypoint: /scripts/init-hive.sh
    image: hive:3.1.2
    ports:
      - 10000:10000
      - 9083:9083
    volumes:
      - "./container_data/hive/warehouse:/shared_data/hive/warehouse"
    depends_on:
      - mssql
      - minio-lake
  
  superset:
    container_name: spark-superset
    build:
      context: ./shared
      dockerfile: Dockerfile.superset
      args:
        - SUPERSET_SECRET_KEY=Supersecretkey!
        - SUPERSET_ADMIN=admin
        - SUPERSET_ADMIN_FIRST_NAME=admin
        - SUPERSET_ADMIN_LAST_NAME=admin
        - SUPERSET_ADMIN_PWD=SupersecretAdminpassw0rd!
        - SUPERSET_ADMIN_EMAIL=admin@nowhere.org
    image: superset:1.5.2
    ports:
      - 8088:8088
    volumes:
      - "./container_data/superset:/superset"