version: '3'
name: "spark_conda"

services:
  postgres:
    hostname: postgres
    networks:
      - sparknet

  pgadmin:
    hostname: pgadmin
    networks:
      - sparknet

  minio-lake:
    hostname: minio-lake
    networks:
      - sparknet
  
  hive-metastore:
    hostname: hive-metastore
    networks:
      - sparknet
  
  superset:
    hostname: superset
    networks:
      - sparknet

  conda_spark:
    container_name: spark-conda
    build: 
      context: .
      dockerfile: ./spark_conda/Dockerfile.conda
      args:
        - HIVE_USER_PASSWORD=Supersecretpassw0rd!
    image: spark-conda:3.3.1
    ports: 
      - 4040:4040
    hostname: spark
    networks:
      - sparknet
    volumes:
      - "../:/workspace"
      - "./container_data/hive/warehouse:/shared_data/hive/warehouse"
    depends_on:
      - minio-lake

networks:
  sparknet:
    driver: bridge