version: '3'
name: "spark_dotnet"

services:
  mssql:
    hostname: mssql
    networks:
      - sparknet

  minio-lake:
    hostname: minio-lake
    networks:
      - sparknet
  
  hive-metastore:
    hostname: hive-metastore
    networks:
      - sparknet

  dotnet_spark:
    container_name: dotnet-spark
    build: 
      context: .
      dockerfile: ./spark_dotnet/Dockerfile.dotnet-spark
      args:
        - DOTNET_CORE_VERSION=3.1
        - DOTNET_SPARK_VERSION=2.1.1
        - SPARK_VERSION=3.2.1
        - HADOOP_VERSION=3.2
        - HIVE_USER_PASSWORD=Supersecretpassw0rd!
    image: dotnet-spark:2.1.1-3.2.1
    ports: 
      - 5567:5567
      - 4040:4040
    networks:
      - sparknet
    volumes:
      - "../:/workspace"
      - "./container_data/hive/warehouse:/shared_data/hive/warehouse"

networks:
  sparknet:
    driver: bridge