version: '3'
name: "spark_dotnet"

services:
  mssql:
    hostname: mssql
    container_name: mssql
    build:
      context: ./shared
      dockerfile: Dockerfile.sql-server
      args:
        - HIVE_USER_PASSWORD=Supersecretpassw0rd!
        - SA_PW=MostSecretPW!
    image: mssql:2019
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    networks:
      - sparknet
    volumes:
      - "./container_data/mssql/log:/var/opt/mssql/log"
      - "./container_data/mssql/data:/var/opt/mssql/data"
      - "./container_data/mssql/secrets:/var/opt/mssql/secrets"
  
  hive-metastore:
    hostname: hive-metastore
    container_name: hive-metastore
    build:
      context: ./shared
      dockerfile: Dockerfile.hive
      args:
        - HIVE_USER_PASSWORD=Supersecretpassw0rd!
    entrypoint: /scripts/init-hive.sh
    image: hive:3.1.2
    ports:
      - 10000:10000
      - 9083:9083
    networks:
      - sparknet
    volumes:
      - "./container_data/hive/warehouse:/shared_data/hive/warehouse"
    depends_on:
      - mssql

  dotnet_spark:
    container_name: dotnet-spark
    build: 
      context: .
      dockerfile: ./spark_dotnet/Dockerfile.dotnet-spark
      args:
        - DOTNET_CORE_VERSION=3.1
        - DOTNET_SPARK_VERSION=2.1.1
        - SPARK_VERSION=3.2.1
        - HADOOP_VERSION=3.2
        - HIVE_USER_PASSWORD=Supersecretpassw0rd!
    image: dotnet-spark:2.1.1-3.2.1
    ports: 
      - 5567:5567
      - 4040:4040
    networks:
      - sparknet
    volumes:
      - "../:/workspace"
      - "./container_data/table_data:/shared_data/table_data"
      - "./container_data/hive/warehouse:/shared_data/hive/warehouse"

networks:
  sparknet:
    driver: bridge